### ISSUE TITLE
Рацпредложение 1

### ISSUE THREAD

**Issue by KorvToti** [procurator5/bet#16]
А возможно, что бы в админке весь тотал был? И если коэффициенты на какой-то из вариантов  тотала автоматически скачались, то этот вариант тотала с этими коэффициентами, также автоматически, отображался бы на сайте? Соответственно те варианты тотала на которые коэффициенты не скачались, на сайте не отображаются.

**Comment by procurator5** [comment]
На другие виды тотала неоткуда загружать коэффициенты ставок
