### ISSUE TITLE
отображать счёт закончившихся игр на основной странице и в "истории"

### ISSUE THREAD

**Issue by KorvToti** [procurator5/bet#22]
Надо бы отображать счёт закончившихся игр на основной странице и  в "истории". По идее клиент должен узнавать счёт у нас на сайте, а не лазить и искать его по другим порталам. Ну и, если возможно, опять же сделать цветовую дифференциацию счёта: игрок угадал - зелёный, не угадал - красный.

**Comment by procurator5** [comment]
Где там на основной странице?
