### ISSUE TITLE
Сделать показ пароля в форме регистрации (там где глаз)

### ISSUE THREAD

**Issue by KorvToti** [procurator5/bet#7]
При регистрации, когда наводишь курсор на поле "логин", под полем выскакивает вкладка "admin", когда наводишь курсор на поле "пароль" под полем выскакивает вкладка что-то типа: "актуально для admin", точно не вспомню, а выйти из аккаунта и посмотреть не получается. Всё это, конечно, не критично, но всё-равно не смотрится. Плюс пароль не отображается, ну это ты и сам знаешь.

**Comment by KorvToti** [comment]
" Плюс пароль не отображается" - Я имею ввиду глазики на пароле не работают.

**Comment by KorvToti** [comment]
А нет, всё понял. Там вылезают логины и пароли  под которыми я раньше заходил. Согласен, так удобнее. Рацпредложение снимаю. Только по глазикам глянь.

**Comment by procurator5** [comment]
Дублирует #21
