### ISSUE TITLE
Сделать отображение значений "В игре" и запрошено к выплате в профиле

### ISSUE THREAD

**Issue by KorvToti** [procurator5/bet#9]
На странице профайл - мой счёт. значение самого счёта отображается корректно, под ним находится значение "в игре", там нули, хотя у меня в игре 0.01 битка. Сами значения "к игре" и "запрошено к выплате" в рублях, а не биткоинах и цифровые значения в них довольно короткие (три цифры с точкой), на биток не хватит.

**Comment by procurator5** [comment]
Значение "К игре" сделал
